# Generated by Django 6.0.5 on 2026-06-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOA_app', '0002_rename_name_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='viewed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket_response',
            name='viewed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
