# Generated by Django 6.0.5 on 2026-06-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOA_app', '0004_mt4data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MT4Data',
        ),
    ]
