# Generated by Django 6.0.5 on 2026-06-20 00:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOA_app', '0005_delete_mt4data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/profile_id/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/profile_pic/'),
        ),
    ]
